/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  CoreBridgeLib,
  CoreBridgeLibInterface,
} from "../../../../src/libraries/CoreBridge.sol/CoreBridgeLib";

const _abi = [
  {
    inputs: [],
    name: "VerificationFailed",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220efe35c8e8fd9e0fcba2cefeffe2a9a36b3f5695e0263607073c9986835697c3564736f6c63430008180033";

type CoreBridgeLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CoreBridgeLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CoreBridgeLib__factory extends ContractFactory {
  constructor(...args: CoreBridgeLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CoreBridgeLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CoreBridgeLib__factory {
    return super.connect(runner) as CoreBridgeLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CoreBridgeLibInterface {
    return new Interface(_abi) as CoreBridgeLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CoreBridgeLib {
    return new Contract(address, _abi, runner) as unknown as CoreBridgeLib;
  }
}
