/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20MockSol from "./ERC20Mock.sol";
export type { erc20MockSol };
import type * as usdcDealerSol from "./UsdcDealer.sol";
export type { usdcDealerSol };
import type * as wormholeRelayer from "./WormholeRelayer";
export type { wormholeRelayer };
import type * as wormholeRelayerTestSol from "./WormholeRelayerTest.sol";
export type { wormholeRelayerTestSol };
export type { QueryRequestBuilder } from "./QueryRequestBuilder";
export type { UpgradeTester } from "./UpgradeTester";
