/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace VmSafe {
  export type LogStruct = {
    topics: BytesLike[];
    data: BytesLike;
    emitter: AddressLike;
  };

  export type LogStructOutput = [
    topics: string[],
    data: string,
    emitter: string
  ] & { topics: string[]; data: string; emitter: string };
}

export interface MockOffchainRelayerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPastDeliveryVaa"
      | "getPastEncodedVaas"
      | "registerChain"
      | "relay((bytes32[],bytes,address)[],bool)"
      | "relay((bytes32[],bytes,address)[],bytes,bool)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPastDeliveryVaa",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPastEncodedVaas",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerChain",
    values: [BigNumberish, AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "relay((bytes32[],bytes,address)[],bool)",
    values: [VmSafe.LogStruct[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "relay((bytes32[],bytes,address)[],bytes,bool)",
    values: [VmSafe.LogStruct[], BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPastDeliveryVaa",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPastEncodedVaas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relay((bytes32[],bytes,address)[],bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relay((bytes32[],bytes,address)[],bytes,bool)",
    data: BytesLike
  ): Result;
}

export interface MockOffchainRelayer extends BaseContract {
  connect(runner?: ContractRunner | null): MockOffchainRelayer;
  waitForDeployment(): Promise<this>;

  interface: MockOffchainRelayerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPastDeliveryVaa: TypedContractMethod<
    [chainId: BigNumberish, deliveryVaaSequence: BigNumberish],
    [string],
    "view"
  >;

  getPastEncodedVaas: TypedContractMethod<
    [chainId: BigNumberish, deliveryVaaSequence: BigNumberish],
    [string[]],
    "view"
  >;

  registerChain: TypedContractMethod<
    [
      chainId: BigNumberish,
      wormholeContractAddress: AddressLike,
      messageTransmitterContractAddress: AddressLike,
      wormholeRelayerContractAddress: AddressLike,
      fork: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "relay((bytes32[],bytes,address)[],bool)": TypedContractMethod<
    [logs: VmSafe.LogStruct[], debugLogging: boolean],
    [void],
    "nonpayable"
  >;

  "relay((bytes32[],bytes,address)[],bytes,bool)": TypedContractMethod<
    [
      logs: VmSafe.LogStruct[],
      deliveryOverrides: BytesLike,
      debugLogging: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPastDeliveryVaa"
  ): TypedContractMethod<
    [chainId: BigNumberish, deliveryVaaSequence: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPastEncodedVaas"
  ): TypedContractMethod<
    [chainId: BigNumberish, deliveryVaaSequence: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerChain"
  ): TypedContractMethod<
    [
      chainId: BigNumberish,
      wormholeContractAddress: AddressLike,
      messageTransmitterContractAddress: AddressLike,
      wormholeRelayerContractAddress: AddressLike,
      fork: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "relay((bytes32[],bytes,address)[],bool)"
  ): TypedContractMethod<
    [logs: VmSafe.LogStruct[], debugLogging: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "relay((bytes32[],bytes,address)[],bytes,bool)"
  ): TypedContractMethod<
    [
      logs: VmSafe.LogStruct[],
      deliveryOverrides: BytesLike,
      debugLogging: boolean
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
