/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  PercentageLib,
  PercentageLibInterface,
} from "../../../../src/libraries/Percentage.sol/PercentageLib";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "mantissa",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "fractionalDigits",
        type: "uint256",
      },
    ],
    name: "InvalidArguments",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "percentage",
        type: "uint16",
      },
    ],
    name: "InvalidPercentage",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220b4f83fe37bb72e06f106780389867c4dc5a6747bf07567824c2266ca0c3ed52764736f6c63430008180033";

type PercentageLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PercentageLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PercentageLib__factory extends ContractFactory {
  constructor(...args: PercentageLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PercentageLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PercentageLib__factory {
    return super.connect(runner) as PercentageLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PercentageLibInterface {
    return new Interface(_abi) as PercentageLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PercentageLib {
    return new Contract(address, _abi, runner) as unknown as PercentageLib;
  }
}
