/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITokenController } from "./ITokenController";
export type { ITokenMinter } from "./ITokenMinter";
