/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  WormholeCctpMessageLib,
  WormholeCctpMessageLibInterface,
} from "../../../../src/legacy/WormholeCctpMessages.sol/WormholeCctpMessageLib";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    name: "InvalidPayloadId",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "PayloadTooLarge",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212209e35bcc361ea06a99e11fee4744908a8a2187f6e57ebf9721014567cb5e0bf4664736f6c63430008180033";

type WormholeCctpMessageLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: WormholeCctpMessageLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class WormholeCctpMessageLib__factory extends ContractFactory {
  constructor(...args: WormholeCctpMessageLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      WormholeCctpMessageLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): WormholeCctpMessageLib__factory {
    return super.connect(runner) as WormholeCctpMessageLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): WormholeCctpMessageLibInterface {
    return new Interface(_abi) as WormholeCctpMessageLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): WormholeCctpMessageLib {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as WormholeCctpMessageLib;
  }
}
