/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOwnable2Step__factory } from "./IOwnable2Step__factory";
export { IPausable__factory } from "./IPausable__factory";
