/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cctpAndTokenBaseSol from "./CCTPAndTokenBase.sol";
export type { cctpAndTokenBaseSol };
import type * as cctpBaseSol from "./CCTPBase.sol";
export type { cctpBaseSol };
import type * as tokenBaseSol from "./TokenBase.sol";
export type { tokenBaseSol };
export type { Base } from "./Base";
