// SPDX-License-Identifier: Apache 2
pragma solidity ^0.8.0;

// This file is auto-generated by gen/cctpDomains.ts.

uint32 constant CCTP_DOMAIN_ETHEREUM = 0;
uint32 constant CCTP_DOMAIN_AVALANCHE = 1;
uint32 constant CCTP_DOMAIN_OPTIMISM = 2;
uint32 constant CCTP_DOMAIN_ARBITRUM = 3;
uint32 constant CCTP_DOMAIN_SOLANA = 5;
uint32 constant CCTP_DOMAIN_BASE = 6;
uint32 constant CCTP_DOMAIN_POLYGON = 7;
uint32 constant CCTP_DOMAIN_SUI = 8;

// Additional Testnet mappings:
uint32 constant CCTP_DOMAIN_SEPOLIA = 0;
uint32 constant CCTP_DOMAIN_OPTIMISM_SEPOLIA = 2;
uint32 constant CCTP_DOMAIN_ARBITRUM_SEPOLIA = 3;
uint32 constant CCTP_DOMAIN_BASE_SEPOLIA = 6;
