/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { WormholeRelayerBasicTest__factory } from "./WormholeRelayerBasicTest__factory";
export { WormholeRelayerTest__factory } from "./WormholeRelayerTest__factory";
