/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDeliveryProvider,
  IDeliveryProviderInterface,
} from "../../../../src/interfaces/deliveryProvider/IDeliveryProvider";

const _abi = [
  {
    inputs: [],
    name: "getRewardAddress",
    outputs: [
      {
        internalType: "address payable",
        name: "rewardAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSupportedKeys",
    outputs: [
      {
        internalType: "uint256",
        name: "bitmap",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "targetChain",
        type: "uint16",
      },
    ],
    name: "getTargetChainAddress",
    outputs: [
      {
        internalType: "bytes32",
        name: "deliveryProviderAddress",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "targetChain",
        type: "uint16",
      },
    ],
    name: "isChainSupported",
    outputs: [
      {
        internalType: "bool",
        name: "supported",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "keyType",
        type: "uint8",
      },
    ],
    name: "isMessageKeyTypeSupported",
    outputs: [
      {
        internalType: "bool",
        name: "supported",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "targetChain",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "currentChainAmount",
        type: "uint256",
      },
    ],
    name: "quoteAssetConversion",
    outputs: [
      {
        internalType: "uint256",
        name: "targetChainAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "targetChain",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "receiverValue",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "encodedExecutionParams",
        type: "bytes",
      },
    ],
    name: "quoteDeliveryPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "nativePriceQuote",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "encodedExecutionInfo",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDeliveryProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IDeliveryProviderInterface {
    return new Interface(_abi) as IDeliveryProviderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDeliveryProvider {
    return new Contract(address, _abi, runner) as unknown as IDeliveryProvider;
  }
}
