/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iDeliveryProviderTypedSol from "./IDeliveryProviderTyped.sol";
export { IDeliveryProvider__factory } from "./IDeliveryProvider__factory";
