/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iMessageTransmitterSol from "./IMessageTransmitter.sol";
export type { iMessageTransmitterSol };
import type * as iTokenMinterSol from "./ITokenMinter.sol";
export type { iTokenMinterSol };
import type * as shared from "./shared";
export type { shared };
export type { ITokenMessenger } from "./ITokenMessenger";
