/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  BytesParsing,
  BytesParsingInterface,
} from "../../../src/libraries/BytesParsing";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "val",
        type: "uint8",
      },
    ],
    name: "InvalidBoolVal",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "encodedLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expectedLength",
        type: "uint256",
      },
    ],
    name: "LengthMismatch",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "offset",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "length",
        type: "uint256",
      },
    ],
    name: "OutOfBounds",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220206dd5b5bc08d3a2875bbf4eaa3b565824bf032f0d5bbff143c3a3e0b963bdf464736f6c63430008180033";

type BytesParsingConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BytesParsingConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BytesParsing__factory extends ContractFactory {
  constructor(...args: BytesParsingConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BytesParsing & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BytesParsing__factory {
    return super.connect(runner) as BytesParsing__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BytesParsingInterface {
    return new Interface(_abi) as BytesParsingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BytesParsing {
    return new Contract(address, _abi, runner) as unknown as BytesParsing;
  }
}
