/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iDeliveryProviderTypedSol from "./IDeliveryProviderTyped.sol";
export type { iDeliveryProviderTypedSol };
export type { IDeliveryProvider } from "./IDeliveryProvider";
