/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWormholeRelayerBase,
  IWormholeRelayerBaseInterface,
} from "../../../../src/interfaces/IWormholeRelayer.sol/IWormholeRelayerBase";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "sequence",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "deliveryQuote",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "paymentForExtraReceiverValue",
        type: "uint256",
      },
    ],
    name: "SendEvent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "deliveryHash",
        type: "bytes32",
      },
    ],
    name: "deliveryAttempted",
    outputs: [
      {
        internalType: "bool",
        name: "attempted",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "deliveryHash",
        type: "bytes32",
      },
    ],
    name: "deliveryFailureBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "deliveryHash",
        type: "bytes32",
      },
    ],
    name: "deliverySuccessBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "chainId",
        type: "uint16",
      },
    ],
    name: "getRegisteredWormholeRelayerContract",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWormholeRelayerBase__factory {
  static readonly abi = _abi;
  static createInterface(): IWormholeRelayerBaseInterface {
    return new Interface(_abi) as IWormholeRelayerBaseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWormholeRelayerBase {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IWormholeRelayerBase;
  }
}
