/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WormholeRelayerBasicTest } from "./WormholeRelayerBasicTest";
export type { WormholeRelayerTest } from "./WormholeRelayerTest";
