/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  QueryType,
  QueryTypeInterface,
} from "../../../../src/libraries/QueryResponse.sol/QueryType";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "received",
        type: "uint8",
      },
    ],
    name: "UnsupportedQueryType",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220880d3480749191fe50be6698045ce4fcd138814ebaad25d100666d14905c329564736f6c63430008180033";

type QueryTypeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: QueryTypeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class QueryType__factory extends ContractFactory {
  constructor(...args: QueryTypeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      QueryType & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): QueryType__factory {
    return super.connect(runner) as QueryType__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): QueryTypeInterface {
    return new Interface(_abi) as QueryTypeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): QueryType {
    return new Contract(address, _abi, runner) as unknown as QueryType;
  }
}
