/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  CctpMessageLib,
  CctpMessageLibInterface,
} from "../../../../src/libraries/CctpMessages.sol/CctpMessageLib";

const _abi = [
  {
    inputs: [],
    name: "InvalidCctpMessageBodyVersion",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidCctpMessageHeaderVersion",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea264697066735822122054e9f9d5da8b15f2f23ce0d7c19df0c1145bbad08c4e1fcb3ae42404cae2bc9664736f6c63430008180033";

type CctpMessageLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CctpMessageLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CctpMessageLib__factory extends ContractFactory {
  constructor(...args: CctpMessageLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CctpMessageLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CctpMessageLib__factory {
    return super.connect(runner) as CctpMessageLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CctpMessageLibInterface {
    return new Interface(_abi) as CctpMessageLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CctpMessageLib {
    return new Contract(address, _abi, runner) as unknown as CctpMessageLib;
  }
}
